spring:
  datasource:
    url: jdbc:mysql://${CINEMA_DB_HOST:localhost}:3306/${CINEMA_DB:cinema}
    username: ${CINEMA_DB_USERNAME:sa}
    password: ${CINEMA_DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update # careful in production!!!
  jackson:
    default-property-inclusion: NON_EMPTY
springdoc:
  swagger-ui:
    path: swagger-ui